### ISSUE TITLE
UI para tabla de analisis sintáctico 

### ISSUE THREAD

**Issue by jesusmartinoza** [jesusmartinoza/Compiladores-B-UASLP#17]
Mostrar lista de estados de manera visual.

Los estados se calculan en el PR https://github.com/jesusmartinoza/Compiladores-B-UASLP/pull/14

**Comment by jesusmartinoza** [comment]
Granja se la rifó en commit 4ff60fc54c1ec5e65db4cb666b6b9ee01afd0a91

**Comment by AlfredoGJ** [comment]
Gracias 😄   🎉 ❤️  
.
.
.
San Luis 👏 👏 👏
