### ISSUE TITLE
Tokenizar cadena

### ISSUE THREAD

**Issue by jesusmartinoza** [jesusmartinoza/Compiladores-B-UASLP#19]
Hola Chivas, me podrían ayudar con un método estático dentro de `Tokenizer` para que reciba una cadena y devuelva una lista de Tokens.

Algo así porfa
```
/// Método para tokenizar cadena
///
/// Ejemplo de entrada: 3 + 4 - 12
/// Salida: Lista que contenga [3, +, 4, -, 12]
public static List<Token> Convert(String input)
{
    ...
}
```

**Comment by snaekier** [comment]
¿Todos los token generados seran terminales?

**Comment by jesusmartinoza** [comment]
@snaekier creo que si :thinking: La neta no se me ocurre un ejemplo que tenga un No terminal

**Comment by snaekier** [comment]
Si en la entrada tengo por ejemplo: 3+ 3, como quieres la salida [3,+] o [3,+,3]

**Comment by jesusmartinoza** [comment]
`[3, +, 3]` por fa, donde cada elemento es una instancia de Token

**Comment by snaekier** [comment]
Parece que ya esta, si gustas checarlo, yo no puedo probarlo en mi maquina porque me marca algunos errores por el compilador

**Comment by jesusmartinoza** [comment]
Va, ahorita lo checo, gracias Pedro!

**Comment by jesusmartinoza** [comment]
Ya lo revisé, funciona bien si tiene espacios porque el método hace un split. Pero cuando el usuario pone `3+3` todo junto, me devuelve una lista con un solo Token [3+3]. 

Creo que @patriciomartinez tiene un código para tokenizar, lo enseñó en la expo que nos tocó hacer de Regex xd

**Comment by snaekier** [comment]
De hecho es como si fuera una palabra, debe de estar separada por un espacio, igual para Regex es lo que se debe de hacer, porque no hay una manera concreta de decir que nuestros token son de tamaño n.
Por eso hasta en la gramatica la manera de separar es un espacio

**Comment by jesusmartinoza** [comment]
🤔 Pero por ejemplo en la tiny una cadena válida es `while(1 > 2)` y se tendría que separar en 
`[while, (, 1, >, 2, )]`. Si hay [formas](https://jack-vanlightly.com/blog/2016/2/3/creating-a-simple-tokenizer-lexer-in-c) pero mejor mañana lo vemos entre todos y también con el profe 😛

**Comment by snaekier** [comment]
Ya te entendi, pero para eso primero debe de pasar por el tokenizado por Regex, donde "while(1 > 2)"
se covertira en "while ( int comp int )" que son los verdaderos token,

**Comment by jesusmartinoza** [comment]
Exacto! :) Eso es lo que necesito para poder hacer la tabla de análisis sintáctico

**Comment by jesusmartinoza** [comment]
Por mientras la armo con el método de Convert usando espacios

**Comment by snaekier** [comment]
Si pero no, para el LR(1) que se va a entregar para el primero compararas una cadena ya tokenizada, el tokenizado ya es para la aplicacion.
Osea metes "while ( int comp int )"
Para la aplicacion ya debes de meter "while(1 > 2)" y se tokeniza para posteriormente analizar
