### ISSUE TITLE
Error en analisis de cadena

### ISSUE THREAD

**Issue by snaekier** [jesusmartinoza/Compiladores-B-UASLP#23]
A la hora de querer analizar el programa Determinates, cuando esta a punto de terminar, en una reduccion, elimina todas las llaves que se encuentran en la pila de la tabla de acciones en lugar de solo eliminar las que corresponden a esta reduccion lo que lleva a que el programa no sea aceptado

**Comment by jesusmartinoza** [comment]
Podrías poner el minimal test case?

**Comment by snaekier** [comment]
Cargar la nueva gramatica (TinyBen2.txt)
Generar la tabla de acciones
En la parte de analisis cargar Determinantes.txt
Comprobar que sea un programa valido
->Aqui es donde dice que no pertenece, en la penultima fila de la tabla de acciones hay 3 o 4 llaves que abren a lo largo de la pila, en la ultima fila no hay ninguna llave que abre en la pila y el numero de estado que pone al final de la pila es 0

¿Si era esto Chuy?

**Comment by jesusmartinoza** [comment]
Si, gracias Pedro. Ahorita lo reviso
