### ISSUE TITLE
Creación de modelos para tokenizado

### ISSUE THREAD

**Issue by jesusmartinoza** [jesusmartinoza/Compiladores-B-UASLP#4]
Esta parte es super importante definirla entre todos porque las clases que definamos aquí serán utilizadas en casi todo el proyecto. 😱 

#### Produccion: 
```
class Production {
  string id;
  List<Token> left; // Conjunto de tokens del lado izquierdo de la flecha 
  List<Token> right;  // Conjunto de tokens del lado derecho de la flecha 
  HashSet<Token> first; // Conjunto de primeros de forma desordenada
   
   ...

}
```

#### Token: 
```
class Token {
  string content;
  bool terminal; // Bandera para indicar si es terminal o no-terminal
  string val; // Guarda lexema o el resultado de evaluar un conjunto de atributos

  public Boolean IsEpsilon()
  {
        return content == "ε";
  }

  public Boolean IsDot()
  {
       return content == "·";
  }
  ...
}
```

**Comment by AlfredoGJ** [comment]
Recuerdenme para que ocupabamos tener los primeros en la producción, lo comente con Charly que es quien hara lo del AFD y concluimos que esta mejor aparte.

**Comment by snaekier** [comment]
Se cambia la lista de tokens de left, por solo un token

class Production {
  string id;
  Token left; //token del lado izquierdo de la flecha 
  List<Token> right;  // Conjunto de tokens del lado derecho de la flecha 
  HashSet<Token> first; // Conjunto de primeros de forma desordenada
}

En cuanto a lo que pregunta Granja, no recuerdo yo para que era

**Comment by jesusmartinoza** [comment]
@AlfredoGJ  era para tener todo más organizado, tiene sentido si cada producción tiene sus primeros y no hacer *otro* diccionario que contenga los primeros por producción

@snaekier se propuso una lista en left para soportar cualquier tipo de gramáticas

**Comment by snaekier** [comment]
Pero no es necesario el soportar todo tipo de gramaticas, pues nosotros ya deberiamos saber el diseño de gramaticas y LR(1) es solo para grámaticas libres de contexto, y estas solo tiene un "token" en la parte izquierda

**Comment by jesusmartinoza** [comment]
Ok, esta chido. Repito, solo se propuso para no hacerlo tan ad hoc. Pero un solo token is ok
