### ISSUE TITLE
Implementación de AvalonEdit

### ISSUE THREAD

**Issue by jesusmartinoza** [jesusmartinoza/Compiladores-B-UASLP#6]
Para escribir la gramática implementar este Nugget. Es fácil de usar y nos permite marcar números de linea y color en la sintaxis. 

https://www.codeproject.com/Articles/161871/Fast-Colored-TextBox-for-syntax-highlighting

**Comment by AlfredoGJ** [comment]
Checamos la herramienta FastColoredTextbox, está muy bien pero hay un inconveniente, es un control de forms.
 Pensabamos usar AvalonEdit, ofrece las mismas funciones y es WPF
https://www.codeproject.com/Articles/42490/Using-AvalonEdit-WPF-Text-Editor

**Comment by jesusmartinoza** [comment]
Se ve cool! Hasta mejor jaja
